---


- name: check if {{ application_name }} application is deployed
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: list
    namespace: "{{ namespace }}"
    name: "{{ application_name }}"
    kind: dc
  register: result

- name: "create service account {{ application_name }}"
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"

- name: copy imagestream template
  template:
    src: "{{ resources_dir }}/{{ binary_imagestream_template }}"
    dest: "{{ work_dir }}/{{ binary_imagestream_template }}"

- name: create imagestream {{ application_name }} in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: imagestream
    name: "{{ application_name }}"
    files:
      - "{{ work_dir }}/{{ binary_imagestream_template }}"

- name: copy application template
  template:
    src: "{{ resources_dir }}/{{ kafdrop_application_template }}"
    dest: "{{ work_dir }}/{{ kafdrop_application_template }}"

# NOTE:  Might be subject to the following error:
#   Internal error occurred: docker.io/obsidiandynamics/kafdrop:3.8.1: toomanyrequests: You have reached your pull rate limit. 
#   You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
- name: deploy {{ application_name }} application
  oc_list:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ kafdrop_application_template }}"
  when: result.ansible_module_results.stderr is defined and result.ansible_module_results.stderr != ""
