---

- name: Deploy Dashbuilder
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/vacsafe_service.yml

  tasks:
    - include: tasks/dashbuilder.yml
