---

- name: UnDeploy all vacsafe artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/vacsafe_service.yml
  vars:
    ACTION: uninstall
    undeploy_psql_bpm: "true"
    undeploy_sso: "false"

  tasks:
  - include: tasks/vacsafe-ui.yml
  - include: tasks/vacsafe-service.yml
  - include: tasks/sso.yml
