---

- name: UnDeploy all vacsafe artifacts
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/all.yml
    - group_vars/tools.yml
    - group_vars/kafka_cluster.yml
    - group_vars/hapi_fhirserver.yml
    - group_vars/vacsafe_service.yml
  vars:
    ACTION: uninstall

  tasks:
  - include: tasks/vacsafe-ui.yml
#  - include: tasks/dashbuilder.yml
  - include: tasks/vacsafe-service.yml
#  - include: tasks/hapi-fhirserver.yml
#  - include: tasks/knative.yml
#  - include: tasks/amq-streams.yml
  - include: tasks/sso.yml
