kind: List
apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: {{ application_name }}
    name: {{ application_name }}
  spec:
    port:
      targetPort: http
    tls:
      termination: edge
    to:
      kind: Service
      name: {{ application_name }}
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    name: {{ application_name }}
    labels:
      expose: "true"
      app: {{ application_name }}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      group: vacsafe
      app: {{ application_name }}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: {{ application_name }}
    name: {{ application_name }}
  spec:
    replicas: 1
    selector:
      group: vacsafe
      app: {{ application_name }}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 3600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          group: vacsafe
          app: {{ application_name }}
      spec:
        containers:
          - image: {{ image_name }}:{{ image_tag }}
            name: {{ application_name }}
            ports:
            - containerPort: 8080
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 3
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              periodSeconds: 30
              timeoutSeconds: 3
            resources:
              limits:
                memory: "1Gi"
                cpu: "500m"
            volumeMounts:
            - name: configs
              mountPath: /opt/app-root/src/public/config.js
              subPath: config.js
            - name: configs
              mountPath: /opt/app-root/src/keycloak.json
              subPath: keycloak.json
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: {{ application_name }}
        serviceAccountName: {{ application_name }}
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            name: {{ application_name }}
          name: configs
    triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
            - {{ application_name }}
          from:
            kind: ImageStreamTag
            name: "{{ application_name }}:{{ image_tag }}"
        type: ImageChange
