---

application_name: "{{ vacsafe_ui_app_name }}"

image_name: "quay.io/redhat_naps_da/vacsafe-ui"
image_tag: 0.0.5

application_template: vacsafe_ui.yml
binary_imagestream_template: binary-imagestream.yml
