---

application_name: "kafdrop"

image_name: "docker.io/obsidiandynamics/kafdrop"
image_tag: 3.27.0

kafdrop_application_template: kafdropservice.yml
binary_imagestream_template: binary-imagestream.yml
