---

- set_fact:
    namespace: "{{ project_name }}"
    resources_dir: "{{ resources_base_dir }}/vacsafe-service"
    work_dir_name: vacsafe-service
- include_role:
    name: ../roles/vacsafe-service
  when: >
    ACTION is not defined or
    ACTION is none or
    ACTION|trim() == "" or
    ACTION|trim() == "install"
- include_role:
    name: ../roles/vacsafe-service
    tasks_from: uninstall
  when: >
    ACTION is defined and
    ACTION|trim() == "uninstall"
