# permissions for end users to view vacsafes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vacsafe-viewer-role
rules:
- apiGroups:
  - cache.redhat.com
  resources:
  - vacsafes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.redhat.com
  resources:
  - vacsafes/status
  verbs:
  - get
