# permissions for end users to edit vacsafes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vacsafe-editor-role
rules:
- apiGroups:
  - cache.redhat.com
  resources:
  - vacsafes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.redhat.com
  resources:
  - vacsafes/status
  verbs:
  - get
